package Libro.cap02.exepciones;
import java.util.ResourceBundle;
public class Aplication 
{
    /*public  Usuario login(String usrname, String password)
    {
        try
        {
            ResourceBundle rb = ResourceBundle.getBundle("usuario");
            String usr = rb.getString("usrname");
            String pwd = rb.getString("password");
            Usuario u = null;
            if( usr.equals(usrname) && pwd.equals(password) )
            {
                u = new Usuario();
                u.setUsrname(usr);
                u.setPassword(pwd);
                u.setNombre( rb.getString("nombre") );
                u.setEmail(rb.getString("email") );
            }
            return u;
        }
        catch(Exception ex)
       {
           throw new RuntimeException("Error verificando datos", ex);
       }
        
    } */
    /*public Usuario login(String usrname, String password)
 throws ErrorFisicoException
 {
 try
 {
 // :
 // aqui nada cambio... todo sigue igual
 // :
 }
 catch(Exception ex)
 {
 throw new ErrorFisicoException(ex);
 }
 }*/
}
